#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020 Dominik Salvet
# github.com/dominiksalvet/afc-scout
#-------------------------------------------------------------------------------
# DESCRIPTION:
#   Checks whether all given shell script files meet a basic code style defined
#   by constants below.
# PARAMETERS:
#   $@ - script paths
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# MAIN FUNCTION
#-------------------------------------------------------------------------------

# DESCRIPTION:
#   Checks the code style of all given scripts against simple predefined rules.
#   Calling of this function should be at the end of this script.
# PARAMETERS:
#   $@ - script paths
main() (
    init_style && # initialize the code style check

    # perform checks for each given script file
    for script_path in "$@"; do
        check_lines_length "$script_path" || return
    done
)

# DESCRIPTION:
#   Initializes constants for code style check.
init_style() {
    readonly MAX_LINE_LENGTH=80 # maximum number of characters per each line
}

#-------------------------------------------------------------------------------
# LINES LENGTH
#-------------------------------------------------------------------------------

# DESCRIPTION:
#   Checks whether each line of a given script file has at most a defined number
#   of characters.
# PARAMETERS:
#   $1 - script path
check_lines_length() (
    lineno=0 # initialize line counter
    while IFS= read -r line; do
        lineno="$((lineno + 1))" # increment line counter
        if [ "${#line}" -gt "$MAX_LINE_LENGTH" ]; then # check line length
            echo "$1:$lineno line has more than $MAX_LINE_LENGTH characters" >&2
            return 1
        fi
    done < "$1"
)

#-------------------------------------------------------------------------------
# CALL MAIN
#-------------------------------------------------------------------------------

main "$@" # call the main function
