#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2020-2022 Dominik Salvet
# https://github.com/dominiksalvet/afc-scout
#-------------------------------------------------------------------------------
# DESCRIPTION:
#   This is the ACPI scout of asus-fan-control used for easier advanced
#   configuration of new laptop devices.
# PARAMETERS:
#   All given arguments are processed as afc-scout's help describes.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# CONSTANTS
#-------------------------------------------------------------------------------

readonly VERSION=2.1.0 # the current version of afc-scout

readonly HELP_MESSAGE='USAGE:
  afc-scout [START END]
  afc-scout help | about'

readonly ABOUT_MESSAGE="afc-scout $VERSION
ACPI scout of asus-fan-control

Copyright 2020-2022 Dominik Salvet
https://github.com/dominiksalvet/afc-scout"

# ACPI related constants
readonly ACPI_CALL_PATH=/proc/acpi/call # entry point of ACPI calls
readonly ACPI_READ_COMMAND='\_SB.PCI0.LPCB.EC0.RRAM' # read from ACPI command

# configuration constants
readonly NICE_RANGES='1335-1342 1431-1438' # possible fan address ranges

#-------------------------------------------------------------------------------
# GENERAL FUNCTIONS
#-------------------------------------------------------------------------------

# DESCRIPTION:
#   Prints a value of a given ACPI address in a decimal form.
# PARAMETERS:
#   $1 - address
read_acpi_value() (
    echo "$ACPI_READ_COMMAND ${1:?}" > "$ACPI_CALL_PATH" && # ACPI read call
    value="$(get_acpi_result)" && # retrieve the ACPI call result
    value="$(echo "$value" | cut -c 1-4)" && # parse value of the output
    value="$((value))" && # convert from hexadecimal to decimal
    echo "$value" # print the final value
)

# DESCRIPTION:
#   Reads and prints the previous ACPI call result, fails on detected errors.
get_acpi_result() (
    result="$(tr -d '\0' < "$ACPI_CALL_PATH")" &&

    if echo "$result" | grep -qi error; then
        echo "acpi call failed with '$result'" >&2; return 1
    else
        echo "$result"
    fi
)

# DESCRIPTION:
#   Beautifies given address and value so that they can be displayed to a user.
#   If a mark is provided, it will print it as well.
# PARAMETERS:
#   $1 - address
#   $2 - value
#   $3 - mark (optional)
beautify_dump() {
    if ! [ "$3" ]; then # without mark
        echo "[$1] = ${2}"
    else # with mark
        echo "[$1] = ${2} <- $3"
    fi
}

#-------------------------------------------------------------------------------
# DUMP FUNCTIONS
#-------------------------------------------------------------------------------

# DESCRIPTION:
#   Prints a mark based on given current, possible start and end addresses.
# PARAMETERS:
#   $1 - current address
#   $2 - possible start address
#   $3 - possible end address
get_nice_range_mark() {
    if [ "$1" -eq "$2" ]; then
        echo 'possible start'
    elif [ "$1" -eq "$3" ]; then
        echo 'possible end'
    fi
}

# DESCRIPTION:
#   Prints a given interesting ACPI address range with additional leading and
#   trailing addresses to see the values trend. It also prints useful marks.
# PARAMETERS:
#   $1 - start address
#   $2 - end address
print_nice_range() (
    addr="$(($1 - 1))" && # start with a lower address (one leading address)
    max_addr="$(($2 + 1))" && # end with a higher address (one trailing address)

    while [ "$addr" -le "$max_addr" ]; do # respect maximum address limit
        value="$(read_acpi_value "$addr")" && # read value
        mark="$(get_nice_range_mark "$addr" "$1" "$2")" &&
        beautify_dump "$addr" "$value" "$mark" &&
        addr="$((addr + 1))" || return # next address
    done
)

# DESCRIPTION:
#   Prints interesting ACPI address ranges and beautifies the output. It also
#   prints the base address of each address range.
print_nice_ranges() (
    for nice_range in $NICE_RANGES; do # for each address range
        start_addr="${nice_range%%-*}" && # range start address
        end_addr="${nice_range##*-}" && # range end address

        echo "------ base address $start_addr ------" && # line separator
        print_nice_range "$start_addr" "$end_addr" || return
    done
)

# DESCRIPTION:
#   Prints values between given ACPI addresses (included) in a decimal form.
# PARAMETERS:
#   $1 - start address
#   $2 - end address
print_range() (
    addr="$1" # initial address

    while [ "$addr" -le "$2" ]; do # respect end address limit
        value="$(read_acpi_value "$addr")" && # read value
        beautify_dump "$addr" "$value" && # print address and its value
        addr="$((addr + 1))" || return # next address
    done
)

#-------------------------------------------------------------------------------
# HELP AND ABOUT
#-------------------------------------------------------------------------------

if [ "$1" = help ]; then
    echo "$HELP_MESSAGE"; exit
elif [ "$1" = about ]; then
    echo "$ABOUT_MESSAGE"; exit
fi

#-------------------------------------------------------------------------------
# CHECK ACPI
#-------------------------------------------------------------------------------

if ! [ -f "$ACPI_CALL_PATH" ]; then # check if ACPI interface file exists
    echo "file $ACPI_CALL_PATH does not exist" >&2; exit 1
fi

id_out="$(id -u)" || exit # check if running as root
if [ "$id_out" -ne 0 ]; then
    echo 'root permissions needed' >&2; exit 1
fi

#-------------------------------------------------------------------------------
# ARGUMENT PROCESSING
#-------------------------------------------------------------------------------

# only no argument or two arguments are allowed
if [ "$#" -eq 0 ]; then
    print_nice_ranges; exit # print beautified interesting address ranges
elif [ "$#" -ne 2 ]; then
    echo 'invalid number of addresses' >&2; exit 1
fi

# check given address range
if ! [ "$1" -ge 0 ] 2>/dev/null; then # positive number
    echo 'invalid start address' >&2; exit 1
fi
if ! [ "$2" -ge 0 ] 2>/dev/null; then # positive number
    echo 'invalid end address' >&2; exit 1
fi
if [ "$1" -gt "$2" ]; then # end address must not be less than start one
    echo 'start address is greater than end address' >&2; exit 1
fi

print_range "$1" "$2" # print custom address range
